# This config file is meant for settings that affect entire website.

# Name of website
title: H.R. Shadhin

# Name to show in the footer
author: H.R. Shadhin

# Short description of your site
share-description: Software Engineer / System Admin / GNU+Linux Lover


# --- List of links in the navigation bar --- #
navbar-links:
  Blog: "https://blog.hrshadhin.me"
  Projects: "projects"
  About Me/Contact: "aboutme"
  Experience: 
    - Skills By Tech: "infographic"
    - Expertise: "areasexpertise"
    - Resume: "resume"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/avatar-icon.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image


# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "hello@hrshadhin.me"
  github: hrshadhin
  stackoverflow: "3132311/tuxbot"
  twitter: hrshadhin
  reddit: hrshadhin
  linkedin: hrshadhin
  youtube: user/crazicoder

# The keywords to associate with your website, for SEO purposes
keywords: "H.R. Shadhin,Software Engineer,System Admin,GNU+Linux Lover,Coding"

# --- Colours / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"


# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Asia/Dhaka"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md